<#
.SYNOPSIS
    NuShell (nu) 现代化终端环境一键安装与美化配置脚本
.DESCRIPTION
    1. 自动执行全终端前置统合备份 (Backup-AllTerminalConfigurations)，支持一键回退；
    2. 包管理器容错降级策略：优先尝试 Chocolatey (最多重试2次)，失败自动配置 WinGet 软件源仓库并安装，最后以 Scoop 兜底；
    3. 自动安装/配置 NuShell 及其现代 CLI 工具集 (Starship, Fastfetch, Eza, Bat, Zoxide)；
    4. 自动生成 env.nu 与 config.nu，配置 UTF-8 中文环境、Starship 赛博朋克提示符、Fastfetch 横幅及现代别名；
    5. 自动检测并注册 Windows Terminal NuShell 配置文件；
    6. 兼容 Windows 11、Windows 10 与 Windows 8.1，兼容 pwsh 与 powershell.exe。
#>
[CmdletBinding()]
param(
    [switch]$NonInteractive,
    [switch]$SkipBackup
)

$ErrorActionPreference = 'Stop'
$projectRoot = $PSScriptRoot
. (Join-Path $projectRoot 'scripts\TerminalSetupCommon.ps1')

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "[+] 开始执行 NuShell (nu) 现代化终端环境安装与美化配置" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# 1. 跨平台环境初始化
Initialize-SetupEnvironment

# 2. 全自动前置统合备份
if (-not $SkipBackup) {
    $null = Backup-AllTerminalConfigurations -Components @('NuShell','Terminal','Shared')
}

# 3. 安装 NuShell 及核心工具链 (Choco 2次重试 -> 自动配置 WinGet 仓库与安装 -> Scoop 兜底)
Write-Host "`n[1/4] 检查并安装 NuShell 及现代 CLI 配套工具链..." -ForegroundColor Yellow

$null = Install-AppWithChocoWingetFallback -Name "NuShell" -ChocoId "nushell" -WingetId "Nushell.Nushell" -ScoopId "nushell" -CommandCheck "nu"
$null = Install-AppWithChocoWingetFallback -Name "Starship" -ChocoId "starship" -WingetId "Starship.Starship" -ScoopId "starship" -CommandCheck "starship"
$null = Install-AppWithChocoWingetFallback -Name "Fastfetch" -ChocoId "fastfetch" -WingetId "Fastfetch-cli.Fastfetch" -ScoopId "fastfetch" -CommandCheck "fastfetch"
$null = Install-AppWithChocoWingetFallback -Name "Eza" -ChocoId "eza" -WingetId "eza-community.eza" -ScoopId "eza" -CommandCheck "eza"
$null = Install-AppWithChocoWingetFallback -Name "Bat" -ChocoId "bat" -WingetId "sharkdp.bat" -ScoopId "bat" -CommandCheck "bat"
$null = Install-AppWithChocoWingetFallback -Name "Zoxide" -ChocoId "zoxide" -WingetId "ajeetdsouza.zoxide" -ScoopId "zoxide" -CommandCheck "zoxide"
Ensure-ScoopBuckets @('nerd-fonts')
Install-ScoopAppsIfMissing @('nerd-fonts/JetBrainsMono-NF')
Ensure-FastfetchConfigured
Ensure-StarshipConfigured

# 4. 配置 NuShell 目录结构与环境文件 (env.nu)
Write-Host "`n[2/4] 配置 NuShell 运行环境 (env.nu)..." -ForegroundColor Yellow
$nuConfigDir = Join-Path $env:APPDATA 'nushell'
if (-not (Test-Path $nuConfigDir)) {
    New-Item -ItemType Directory -Path $nuConfigDir -Force | Out-Null
}
$nuAutoloadDir = Join-Path $nuConfigDir 'vendor\autoload'
if (-not (Test-Path $nuAutoloadDir)) {
    New-Item -ItemType Directory -Path $nuAutoloadDir -Force | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false

$envNuPath = Join-Path $nuConfigDir 'env.nu'
$envNuContent = @'
# =============================================================================
# NuShell Environment Configuration (env.nu)
# Generated by Windows Terminal Beautification Suite
# =============================================================================

# UTF-8 Encoding
$env.LANG = "zh_CN.UTF-8"
$env.LC_ALL = "zh_CN.UTF-8"

# Autoload directory
try { mkdir (($nu.data-dir? | default ("~/.local/share/nushell" | path expand)) | path join "vendor/autoload") } catch {}
'@

Set-TerminalText $envNuPath $envNuContent
Write-Host "[OK] 已生成 NuShell 环境配置: $envNuPath" -ForegroundColor Green

# 5. 配置 Starship & Zoxide 自动加载插件 (vendor/autoload)
Write-Host "`n[3/4] 配置 Starship 提示符与 Zoxide 目录快跳..." -ForegroundColor Yellow
$starshipNuPath = Join-Path $nuAutoloadDir 'starship.nu'
$starshipCmd = Get-Command starship -ErrorAction SilentlyContinue
if ($starshipCmd) {
    try {
        $starshipScript = & $starshipCmd.Source init nu 2>$null
        if ($LASTEXITCODE -ne 0 -or -not $starshipScript) { throw 'Starship generation failed.' }
        if ($starshipScript) {
            Set-TerminalText $starshipNuPath ($starshipScript -join "`n")
            Write-Host "[OK] 已配置 NuShell Starship 提示符: $starshipNuPath" -ForegroundColor Green
        }
    } catch {
        throw "Starship generation failed: $_"
    }
} else {
    Write-Host "[*] 未在当前 PATH 中检测到 Starship，跳过 Starship 自动加载生成" -ForegroundColor DarkGray
}

$zoxideNuPath = Join-Path $nuAutoloadDir 'zoxide.nu'
$zoxideCmd = Get-Command zoxide -ErrorAction SilentlyContinue
if ($zoxideCmd) {
    try {
        $zoxideScript = & $zoxideCmd.Source init nushell 2>$null
        if ($LASTEXITCODE -ne 0 -or -not $zoxideScript) { throw 'Zoxide generation failed.' }
        if ($zoxideScript) {
            Set-TerminalText $zoxideNuPath ($zoxideScript -join "`n")
            Write-Host "[OK] 已配置 NuShell Zoxide 插件: $zoxideNuPath" -ForegroundColor Green
        }
    } catch {
        throw "Zoxide generation failed: $_"
    }
}

# 6. 配置 NuShell 主配置文件 (config.nu)
Write-Host "`n[4/4] 配置 NuShell 主配置 (config.nu)..." -ForegroundColor Yellow
$configNuPath = Join-Path $nuConfigDir 'config.nu'
$configNuContent = @'
# =============================================================================
# NuShell Main Configuration (config.nu)
# Generated by Windows Terminal Beautification Suite
# =============================================================================

# 1. 基础体验优化
$env.config.show_banner = false
$env.config = ($env.config? | default {} | merge {
    show_banner: false
    table: {
        mode: "rounded"
        index_mode: "auto"
    }
    history: {
        max_size: 100000
        sync_on_enter: true
        file_format: "plaintext"
    }
})

# 2. 启动横幅 (Fastfetch)
if ($nu.is-interactive? | default false) and (($env.PROFILE_BANNER? | default "1") != "0") and (which fastfetch | is-not-empty) {
    let conf_file = ("~/.config/fastfetch/config.jsonc" | path expand)
    if ($conf_file | path exists) {
        ^fastfetch -c $conf_file
    } else {
        ^fastfetch
    }
}

# 3. 现代化功能就绪卡片
if ($nu.is-interactive? | default false) and (($env.PROFILE_TIPS? | default "1") != "0") {
if (which yazi | is-not-empty) {
    print "  ✓ yazi 文件管理器已集成 (命令: yazi)"
}
if (which bat | is-not-empty) and (which eza | is-not-empty) {
    print "  ✓ bat + eza 现代化预览集成完成"
}
if (which eza | is-not-empty) {
    print "  ✓ eza 现代化 ls 已启用 (别名: ll, la, lt)"
}
if (which bat | is-not-empty) {
    print "  ✓ bat 代码高亮查看已启用 (别名: cat)"
}
if (which zoxide | is-not-empty) {
    print "  ✓ zoxide 智能跳转已启用 (命令: z)"
}
if (which fastfetch | is-not-empty) {
    print "  ✓ fastfetch 系统信息工具已启动"
}
print ""
}

# 4. 现代化命令行别名 (Eza, Bat, Git, Dev & System Tools)
alias .. = cd ..
alias ... = cd ../..
alias .... = cd ../../..

alias ll = ^eza -l --icons --git --header
alias la = ^eza -la --icons --git --header
alias lt = ^eza --tree --level=2 --icons
alias lt3 = ^eza --tree --level=3 --icons

alias cat = ^bat --paging=never

alias g = git
alias gst = git status
alias ga = git add
alias gaa = git add --all
alias gc = git commit -m
alias gcm = git commit -m
alias gca = git commit --amend
alias gco = git checkout
alias gcb = git checkout -b
alias gb = git branch
alias gsw = git switch
alias glog = git log --oneline --graph --decorate
alias gpull = git pull
alias gps = git push
alias gd = git diff
alias gdiff = git diff
alias lg = lazygit
alias lzg = lazygit
alias lzd = lazydocker

alias v = nvim
alias c = code
alias y = yazi
alias ports = netstat -ano
alias myip = ^fastfetch -s localip
'@

Set-TerminalText $configNuPath $configNuContent
Write-Host "[OK] 已生成 NuShell 主配置: $configNuPath" -ForegroundColor Green

# 7. 注册 Windows Terminal NuShell 配置文件 (若已安装 WT)
Register-TerminalShellProfile -Shell NuShell

Write-Host "`n============================================================" -ForegroundColor Green
Write-Host "[OK] NuShell 安装与美化配置完成！" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host "[提示] 您可以在 Windows Terminal 中选择 NuShell 标签页，或直接在命令行输入 nu 体验！" -ForegroundColor Cyan
